"""Extract all 52 Learnist lessons into lessons_seed_data.json.

The site is a static vanilla-JS app: lesson content ships in data.js and
content-bank.js as `window.LEARNIST_LESSONS` / `window.LEARNIST_SKILL_CONTENT`,
and the Writing/Speaking prompts are generated by the page's own
`writingPrompt()` and `scenario()` functions. Scraping only the rendered DOM
can't work (the listening transcript stays locked until a quiz attempt), so
this script:

1. loads the page in Chromium and reads the data through the page's own JS;
2. logs in as a demo teacher (unlocks every lesson). A lesson with an empty
   rule gets the fallback guide the Grammar tab shows instead (captured from
   the feedback after a deliberately weak attempt in this throwaway browser);
   `grammar_rules_source` records which one was used;
3. opens each lesson and checks that the rendered Reading / Writing /
   Speaking tabs match what was extracted.

Usage:  .venv/bin/python final_scraper.py [--skip-verify]
"""

import json
import sys
from pathlib import Path

from bs4 import BeautifulSoup
from playwright.sync_api import Page, sync_playwright

URL = "https://quiet-fudge-c33d17.netlify.app/"
OUTPUT = Path(__file__).with_name("lessons_seed_data.json")
EXPECTED_LESSONS = 52

# Runs inside the page, so prompts come from the site's own generators.
EXTRACT_JS = """() => {
  const bank = window.LEARNIST_SKILL_CONTENT || {};
  return (window.LEARNIST_LESSONS || []).map(l => ({
    lesson: l,
    skills: bank[l.number] || bank[String(l.number)] || null,
    writingPrompt: typeof writingPrompt === 'function' ? writingPrompt(l) : null,
    speakingPrompt: typeof scenario === 'function' ? scenario(l) : null,
  }));
}"""


def clean(value):
    """Trimmed string, or None when missing/blank."""
    if not isinstance(value, str):
        return None
    value = value.strip()
    return value or None


def html_to_text(value):
    """Prompts are inserted as HTML; strip any tags and entities."""
    value = clean(value)
    if value is None:
        return None
    return clean(BeautifulSoup(value, "html.parser").get_text())


def questions(raw):
    return [
        {
            "question": clean(q.get("q")),
            "options": [clean(o) for o in q.get("o") or []],
            "answer_index": q.get("a"),
            "hint": clean(q.get("h")),
        }
        for q in raw or []
        if isinstance(q, dict)
    ]


def vocabulary(raw):
    items = []
    for entry in raw or []:
        word, definition, example = (list(entry) + [None, None, None])[:3]
        items.append(
            {
                "word": clean(word),
                "definition": clean(definition),
                "example": clean(example),
            }
        )
    return items


def transcript(listening):
    """Same "Speaker: line" layout the Listening tab shows."""
    lines = listening.get("lines") or []
    speakers = listening.get("speakers") or []
    rendered = []
    for entry in lines:
        index, text = (list(entry) + [None, None])[:2]
        text = clean(text)
        if text is None:
            continue
        name = (
            speakers[index]
            if isinstance(index, int) and 0 <= index < len(speakers)
            else f"Speaker {(index or 0) + 1}"
        )
        rendered.append(f"{name}: {text}")
    return "\n".join(rendered) or None


def to_record(raw):
    lesson = raw["lesson"]
    skills = raw.get("skills") or {}
    reading = skills.get("reading") or {}
    listening = skills.get("listening") or {}

    return {
        "lesson_number": lesson.get("number"),
        "original_number": lesson.get("originalNumber"),
        "semester": lesson.get("semester"),
        "title": clean(lesson.get("title")),
        "grammar_focus": clean(lesson.get("focus")),
        "cefr_level": clean(skills.get("level")),
        "topic": clean(skills.get("topic")),
        "task_meta": [m for m in map(clean, lesson.get("taskMeta") or []) if m],
        "grammar_rules": clean(lesson.get("rule")),
        "grammar_rules_source": "lesson" if clean(lesson.get("rule")) else None,
        "reading_passage": clean(reading.get("text")),
        "reading_format": clean(reading.get("format")),
        "reading_vocabulary": vocabulary(reading.get("vocab")),
        "reading_questions": questions(reading.get("questions")),
        "listening_transcript": transcript(listening),
        "listening_format": clean(listening.get("format")),
        "listening_speakers": [s for s in map(clean, listening.get("speakers") or []) if s],
        "listening_questions": questions(listening.get("questions")),
        "writing_prompt": html_to_text(raw.get("writingPrompt")),
        "speaking_prompt": html_to_text(raw.get("speakingPrompt")),
    }


def normalize(text):
    return " ".join((text or "").split())


def log_in_as_teacher(page: Page):
    """Demo accounts live in this browser's localStorage only."""
    page.wait_for_selector("#auth:not(.hidden)")
    page.click("#roleTabs [data-role=teacher]")
    page.fill("#authName", "Seed Scraper")
    page.fill("#authUser", "seed_scraper")
    page.fill("#authPass", "seed-scraper")
    page.click("#loginBtn")
    page.wait_for_selector("#app:not(.hidden)")


def open_lesson(page: Page, n):
    page.click("#nav button[data-page=topics]")
    page.click(f"article.lesson-card[data-lesson='{n}']")
    page.wait_for_selector("[data-skill=reading]")


def capture_fallback_rule(page: Page, n):
    """The rule box the Grammar tab shows after a failed attempt."""
    open_lesson(page, n)
    page.click("[data-skill=grammar]")
    page.fill("#grammarAnswer", "one two three four five six")
    page.click("#checkGrammar")
    box = page.wait_for_selector("#grammarFeedback .rule-box")
    return clean(box.inner_text())


def verify_rendered(page: Page, records):
    """Open every lesson and compare the rendered tabs with the data."""
    mismatches = []
    for record in records:
        n = record["lesson_number"]
        open_lesson(page, n)

        checks = [
            ("reading", "#content", record["reading_passage"]),
            ("writing", ".scenario h3", record["writing_prompt"]),
            ("speaking", ".scenario h3", record["speaking_prompt"]),
        ]
        for skill, selector, expected in checks:
            if expected is None:
                continue
            page.click(f"[data-skill={skill}]")
            page.wait_for_selector(selector)
            shown = normalize(page.inner_text(selector))
            # The reading tab wraps the passage in other UI text, so check
            # that the passage's opening is on screen.
            needle = normalize(expected)[:120] if skill == "reading" else normalize(expected)
            ok = needle in shown if skill == "reading" else needle == shown
            if not ok:
                mismatches.append((n, skill, needle[:80], shown[:80]))
    print(f"  verified {len(records)} lessons")
    return mismatches


def main():
    skip_verify = "--skip-verify" in sys.argv

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        page.goto(URL, wait_until="networkidle")
        page.wait_for_function(
            "Array.isArray(window.LEARNIST_LESSONS) && !!window.LEARNIST_SKILL_CONTENT"
        )

        records = [to_record(raw) for raw in page.evaluate(EXTRACT_JS)]
        records.sort(key=lambda r: r["lesson_number"] or 0)

        log_in_as_teacher(page)
        for record in records:
            if record["grammar_rules"] is None:
                rule = capture_fallback_rule(page, record["lesson_number"])
                if rule:
                    record["grammar_rules"] = rule
                    record["grammar_rules_source"] = "site_fallback_guide"
        fallbacks = [
            r["lesson_number"]
            for r in records
            if r["grammar_rules_source"] == "site_fallback_guide"
        ]

        mismatches = [] if skip_verify else verify_rendered(page, records)
        browser.close()

    OUTPUT.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    core = [
        "title",
        "grammar_rules",
        "reading_passage",
        "listening_transcript",
        "writing_prompt",
        "speaking_prompt",
    ]
    print(f"Wrote {len(records)} lessons to {OUTPUT.name}")
    for field in core:
        missing = [r["lesson_number"] for r in records if not r[field]]
        print(f"  {field:<22} {len(records) - len(missing):>2}/{len(records)}"
              + (f"  missing: {missing}" if missing else ""))

    if fallbacks:
        print(f"  grammar_rules from the site's generic fallback guide: {fallbacks}")
    if len(records) != EXPECTED_LESSONS:
        print(f"WARNING: expected {EXPECTED_LESSONS} lessons, got {len(records)}")
    if not skip_verify:
        if mismatches:
            print(f"WARNING: {len(mismatches)} rendered-tab mismatches:")
            for m in mismatches:
                print("   ", m)
        else:
            print("Rendered-tab check: every lesson's Reading/Writing/Speaking matches.")


if __name__ == "__main__":
    main()
