-- Server-side listening audio: an `audio_url` on every lesson and a public
-- storage bucket holding the MP3s generated by `generate_audios.py`.
--
-- Safe to re-run. Paste into the Supabase SQL Editor, then run
-- `.venv/bin/python generate_audios.py` to fill the column.
--
-- Security model:
--   * The bucket is public, so the MP3s stream from a plain CDN URL with no
--     signed request and no auth header — `just_audio` just gets a URL.
--   * Reads are the only thing granted. Uploads and deletes have no policy,
--     so they are possible only with the service_role key (which bypasses
--     RLS) — i.e. from the generator script, never from the app.

-- ---------------------------------------------------------------------------
-- 1. lessons.audio_url
-- ---------------------------------------------------------------------------

alter table public.lessons
  add column if not exists audio_url text;

comment on column public.lessons.audio_url is
  'Public URL of the Neural TTS rendering of listening_transcript, in the '
  'listening_audios storage bucket. Null until generate_audios.py has run.';

-- ---------------------------------------------------------------------------
-- 2. Storage bucket
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'listening_audios',
  'listening_audios',
  true,
  10485760,                 -- 10 MB; a 52-lesson transcript renders well under 1 MB
  array['audio/mpeg']
)
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ---------------------------------------------------------------------------
-- 3. Row Level Security on the objects
-- ---------------------------------------------------------------------------

-- storage.objects already has RLS enabled by Supabase; this is a no-op that
-- documents the dependency.
alter table storage.objects enable row level security;

drop policy if exists "Listening audios are publicly readable" on storage.objects;
create policy "Listening audios are publicly readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'listening_audios');
